### PR TITLE
fix(origo): tls chunk decryption

### LINKED ISSUE #504: Error: ProofError(WitnessGenerator(SerdeJson(Error("EOF while parsing a value", line: 1, column: 0))))
Hi, according to the README, I started the Notary in one terminal and the Origo in another but with self-defined [client.origo_tcp_local.json](https://gist.githubusercontent.com/ujnss/7185d223d2523f4001851903805f2e74/raw/52367c5ced8cb3e00b10f33e658375b774b9965e/client.origo_tcp_local.json) (The target url is https://www.apple.com/shop/experience-meta).

In the Origo end encountered an error: [the full log](https://gist.githubusercontent.com/ujnss/416b14c0b96a61bfd4eb84b3e66f2ae5/raw/f0d8911e9e38c69fe6c4bfefa16539faff7d3072/origo-apple.log).

```log
...
2025-02-21T08:33:17.672153Z DEBUG proofs::program::manifest: 255: aad: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 3, 3, 0, 156]
2025-02-21T08:33:17.672165Z DEBUG proofs::program::manifest: 256: plaintext: []
2025-02-21T08:33:17.672176Z DEBUG proofs::program::manifest: 257: ciphertext: []
2025-02-21T08:33:17.672189Z DEBUG proofs::program::manifest: 334: plaintext: 0
2025-02-21T08:33:17.672200Z DEBUG proofs::program::manifest: 335: plaintext: []
2025-02-21T08:33:17.672229Z DEBUG proofs::program::manifest: 372: HTTP body: 0
Error: ProofError(WitnessGenerator(SerdeJson(Error("EOF while parsing a value", line: 1, column: 0))))
```

For comparison, if I replace the url `https://www.apple.com/shop/experience-meta` with `https://gist.githubusercontent.com/mattes/23e64faadb5fd4b5112f379903d2572e/raw/74e517a60c21a5c11d94fec8b572f68addfade39/example.json` in file [client.origo_tcp_local.json](https://gist.githubusercontent.com/ujnss/7185d223d2523f4001851903805f2e74/raw/52367c5ced8cb3e00b10f33e658375b774b9965e/client.origo_tcp_local.json), I don't get the above error.

system infos:
```
OS: Ubuntu 22.04, x86_64
rustc: 1.81.0
cargo: 1.81.0
```

### PR DESCRIPTION
**Pull request by lonerapier**
blocked by https://github.com/pluto/tls-origo-legacy/pull/2

closes #504 

---

We were not handling seq from tls chunks properly, and setting them based on assumption. Some servers can send arbitrary session key change request, that can change seq.

Example #504:
after client has sent the request with seq: 0
servers sends 2 session key change request: seq: 0,1
then sends response application data: seq: 2

- fixes ciphertext decryption logic using correct seq
- fixes notary ciphertext digest computation logic (checks every first ciphertext chunks)

TODO:
- fix `seq` in manifest
  - Currently, we're assuming that server won't change session key between the packets, i.e. once it starts sending the actual response, the session keys will remain same. 
  - But that isn't true, and server has the ability to change session keys anytime during the session.
- allow for arbitrary `ciphertext_digest` permutation logic in notary

### CODE REVIEW

**Comment by devloper** [comment]
Can you also update the tls_parser in notary to handle this decryption for tee mode?  We should consolidate these places into one piece of code.

**Comment by devloper** [comment]
Will approve once the dependency PR is merged and passing.

File: client/src/tls.rs [hunk 1]
```diff
@@ -125,30 +117,56 @@ pub(crate) fn decrypt_tls_ciphertext(witness: &WitnessData) -> Result<TLSEncrypt
...
   let response_iv: [u8; 12] = witness.response.aead_iv[..12].try_into()?;
-  let response_seq = request_seq + request_plaintext.len() as u64;
   let (response_ciphertext, response_plaintext): (Vec<_>, Vec<_>) = witness
     .response
-    .ciphertext
+    .decrypt_chunk
     .iter()
     .enumerate()
-    .map(|(i, ct_chunk)| {
+    .map(|(i, DecryptChunk { ciphertext: ct_chunk, seq })| {
```
Comment (devloper) [inline client/src/tls.rs:167]: nit, remove the enumerate now that we don't use `i`

**Review by devloper — APPROVED** [review]
lgtm
